---
apiVersion: v1
kind: Secret
metadata:
  name: rhsummit2023-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23DevRHEL/rhsummit2023-gateway-gitops
